export const BUG_CREATE_REQUEST = "BUG_CREATE_REQUEST";
export const BUG_CREATE_SUCCESS = "BUG_CREATE_SUCCESS";
export const BUG_CREATE_FAIL = "BUG_CREATE_FAIL";
export const BUG_CREATE_RESET = "BUG_CREATE_RESET";

export const BUG_LIST_REQUEST = "BUG_LIST_REQUEST";
export const BUG_LIST_SUCCESS = "BUG_LIST_SUCCESS";
export const BUG_LIST_FAIL = "BUG_LIST_FAIL";

export const BUG_DETAILS_REQUEST = "BUG_DETAILS_REQUEST";
export const BUG_DETAILS_SUCCESS = "BUG_DETAILS_SUCCESS";
export const BUG_DETAILS_FAIL = "BUG_DETAILS_FAIL";

export const BUG_DELETE_REQUEST = "BUG_DELETE_REQUEST";
export const BUG_DELETE_SUCCESS = "BUG_DELETE_SUCCESS";
export const BUG_DELETE_FAIL = "BUG_DELETE_FAIL";

export const BUG_UPDATE_REQUEST = "BUG_UPDATE_REQUEST";
export const BUG_UPDATE_SUCCESS = "BUG_UPDATE_SUCCESS";
export const BUG_UPDATE_FAIL = "BUG_UPDATE_FAIL";
export const BUG_UPDATE_RESET = "BUG_UPDATE_RESET";